{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.modules.home.zapret;
in
{
  options.modules.home.zapret = {
    enable = mkEnableOption "user zapret aliases and helpers";
    
    # Персональные домены
    personalDomains = mkOption {
      type = types.listOf types.str;
      default = [];
      description = "Your personal domains to add to zapret";
    };
    
    # Кастомные алиасы
    extraAliases = mkOption {
      type = types.attrsOf types.str;
      default = {};
      description = "Extra zapret-related aliases";
    };
    
    # Автоматическое обновление
    autoUpdate = mkOption {
      type = types.bool;
      default = false;
      description = "Automatically update zapret configs daily";
    };
  };

  config = mkIf cfg.enable {
    # Основные алиасы
    home.shellAliases = {
      # Статус и логи
      zapret-status = "systemctl status zapret-discord-youtube";
      zapret-logs = "journalctl -u zapret-discord-youtube -f";
      zapret-logs-now = "journalctl -u zapret-discord-youtube --since '5 minutes ago'";
      
      # Управление сервисом
      zapret-restart = "sudo systemctl restart zapret-discord-youtube";
      zapret-stop = "sudo systemctl stop zapret-discord-youtube";
      zapret-start = "sudo systemctl start zapret-discord-youtube";
      zapret-reload = "sudo systemctl reload zapret-discord-youtube";
      
      # Смена стратегии (удобно!)
      zapret-config = "sudo sed -i 's/^config=.*/config=\"'$1'\"/' /run/zapret/config && sudo systemctl restart zapret-discord-youtube";
      
      # Проверка работы
      zapret-check = "curl -I https://discord.com 2>/dev/null | head -n 1 && curl -I https://youtube.com 2>/dev/null | head -n 1";
    } // cfg.extraAliases;

    # Файл с персональными доменами
    home.file.".config/zapret/personal-domains.txt" = mkIf (cfg.personalDomains != []) {
      text = ''
        # Personal domains added by user
        # Generated by home-manager - do not edit manually
        ${lib.concatStringsSep "\n" cfg.personalDomains}
      '';
    };

    # Функция для быстрой смены стратегии
    home.file.".local/bin/zapret-switch" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        # Quick zapret strategy switcher
        
        STRATEGY="''${1:-general(ALT)}"
        
        echo "🔄 Switching zapret to: $STRATEGY"
        
        if [ -f /run/zapret/config ]; then
          sudo sed -i "s/^config=.*/config=\"$STRATEGY\"/" /run/zapret/config
          sudo systemctl restart zapret-discord-youtube
          echo "✅ Switched to: $STRATEGY"
          echo ""
          echo "📊 Status:"
          systemctl status zapret-discord-youtube --no-pager | head -3
        else
          echo "❌ Zapret config not found. Is the service running?"
        fi
      '';
    };

    # Системд-юнит для автообновления (опционально)
    systemd.user.services.zapret-update = mkIf cfg.autoUpdate {
      Unit = {
        Description = "Update zapret configs daily";
      };
      Service = {
        Type = "oneshot";
        ExecStart = "${pkgs.nix}/bin/nix flake update /home/lidjen/Flake && ${pkgs.systemd}/bin/systemctl --user restart zapret-discord-youtube";
      };
    };
    
    systemd.user.timers.zapret-update = mkIf cfg.autoUpdate {
      Unit = {
        Description = "Daily zapret update";
      };
      Timer = {
        OnCalendar = "daily";
        Persistent = true;
      };
      Install = {
        WantedBy = ["timers.target"];
      };
    };
  };
}
